export const INITIAL_DRAW_COUNT = 7
export const TOTAL_DRAWS = 35
export const TOTAL_POWERBALL = 20
export const LOTTO_QUERY_KEY = 'lotto_picks'
export const POWER_BALL_LABEL = "PB"
export const COMPANY_ID = "GoldenCasket"
export const MAX_DRAW_COUNT_PER_PRODUCT = 1
export const PRODUCT_FILTER = "Powerball"
export const POWERBALL_HEADER = "Select Your Powerball"
